name: CI

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
      - name: Install modules
        run: bun install
      - name: Check formatting with Prettier
        run: bun format:check
      - name: Check quality with ESLint
        run: bun lint
      - name: Check types compile
        run: bun type-check
      - name: Check tests pass
        run: bun test
      - name: Check app builds
        run: bun bake
